public class Operator {
    // Alternative for enum

    public static String EQUALS = '=';
    public static String NOT_EQUALS = '!=';
    public static String LESS_THAN = '<';
    public static String GREATER_THAN = '>';
    public static String LESS_OR_EQUAL = '<=';
    public static String GREATER_OR_EQUAL = '>=';
    public static String LIKE_X = 'LIKE';
    public static String IN_X = 'IN';
    public static String NOT_IN_X = 'NOT IN';
}